### ISSUE TITLE
Period of TickerBehavior cannot be modified after constructing the object

### ISSUE THREAD

**Issue by shortstheory** [org-arl/fjage#67]
I have a UnetAgent with a TickerBehavior which runs at a certain interval. I want this interval to be configurable by the user by using a parameter of the UnetAgent which can be changed at runtime.

The problem is, `period` is a private member of TickerBehavior. Looking at the fjage source for TickerBehavior, I can see that the period can only be set once in the constructor. Would it be possible to add a setter for `period` so I can change the interval my TickerBehavior runs at on the fly?

**Comment by mchitre** [comment]
Changing `period` which the ticker is ticking is somewhat tricky. Not because it's hard to do, but because the intended behavior is unclear. Should the ticker change the current tick and hence the `wakeupTime`? Or should it change from the next tick?

A cleaner solution is to simply `stop()` the old `TickerBehavior`, and create a new `TickerBehavior` with the correct `period`. Is there a reason you can't do this?

**Comment by shortstheory** [comment]
Oh I see. Accordingly, I have made the change to create a new TickerBehavior each time the parameter is set while stopping the old Behavior.
